### ISSUE TITLE
Run server on ephemeral port

### ISSUE THREAD

**Issue by JonasVautherin** [eerimoq/asyncudp#11]
Is there a way to run a server on an ephemeral port, with e.g.:

```python
socket = await asyncudp.create_socket(local_addr=('0.0.0.0', 0))
```

I haven't seen a way to fetch the port in that case. Would you be open to a PR that would add that? Would you have some advice before I start looking into it? :blush:

**Comment by erik-moqvist** [comment]
This exists:

```python
socket = await asyncudp.create_socket(local_addr=('0.0.0.0', 0))
print(socket.getsockname())
```

**Comment by JonasVautherin** [comment]
Oh right, I missed it in the code after convincing myself that this was the whole API: https://asyncudp.readthedocs.io/en/latest/#functions-and-classes

Thanks a lot! :heart:

**Comment by eerimoq** [comment]
Nice catch. I'll update the docs.
