### ISSUE TITLE
ConnectionRefusedError on second `sendto()` call

### ISSUE THREAD

**Issue by JonasVautherin** [eerimoq/asyncudp#12]
I am trying to repeatedly send to 127.0.0.1:9999, like this:

```python
import asyncio
import asyncudp


async def main():
    sock = await asyncudp.create_socket(remote_addr=('127.0.0.1', 9999))

    while True:
        print("sending hello")
        sock.sendto(b'Hello!')


asyncio.run(main())
```

However it fails at the second call of `sendto()` with `ConnectionRefusedError`. Why is that? Shouldn't I be able to call `sendto` like this?

**Comment by eerimoq** [comment]
If there is no socket receiving the packets the kernel replies with ICMP Destination unreachable. One could argue that sendto() should ignore the error. Not sure what the best behavior is. The current behavior is the same as the python socket module behavior.

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/176810/223926430-386a9852-cb36-44cd-9a8e-09e99d24df24.png">

**Comment by JonasVautherin** [comment]
Oh I did not know that :see_no_evil:. If I send to a remote address not on the same host, then that's fine, but if I send locally, then the kernel apparently checks if someone is listening on the other side.

Good to know, thanks again for the help!
