### ISSUE TITLE
Add .settimeout method to handle situations when a server is not responding

### ISSUE THREAD

**Issue by lex-pec** [eerimoq/asyncudp#9]
I found your library very useful for me, @eerimoq. Thank you!

**Problem:**
But using it I ran into a problem handling an error when a client stopped receiving data or pings from the server. It would be great if your module will be able to handle this kind of error. It is expected to be like a [socket.settimeout()](https://docs.python.org/3/library/socket.html#socket.socket.settimeout) from the socket package.

I am not sure my coding skills can help resolve it, I will try to make a request, but it could take a very long time.

**Comment by eerimoq** [comment]
You can use `wait_for`:

```python
import asyncio
import asyncudp

async def main():
    sock = await asyncudp.create_socket(local_addr=('127.0.0.1', 9999))

    try:
        print(await asyncio.wait_for(sock.recvfrom(), 10))
    except asyncio.TimeoutError:
        print('No data received in 10 seconds.')

    sock.close()

asyncio.run(main())
```

**Comment by lex-pec** [comment]
It helped, thank you!
